#!/bin/bash
# Photo Verification Admin - Installation & Quick Start Guide
# Last Updated: Feb 27, 2026

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║   Photo Verification Admin Dashboard - Installation Guide     ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}Step 1: Create Test Moderator Account${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "cd backend"
echo "node create-test-moderator.js"
echo ""
echo -e "${GREEN}✓ Creates: moderator@test.com / moderator123${NC}"
echo ""

echo -e "${BLUE}Step 2: Start Backend Server${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "cd backend"
echo "npm run dev"
echo ""
echo -e "${GREEN}✓ Server runs on: http://localhost:5000${NC}"
echo ""

echo -e "${BLUE}Step 3: Start Frontend (New Terminal)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "npm run dev"
echo ""
echo -e "${GREEN}✓ App runs on: http://localhost:3001${NC}"
echo ""

echo -e "${BLUE}Step 4: Login to App${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Email:    moderator@test.com"
echo "Password: moderator123"
echo ""

echo -e "${BLUE}Step 5: Access Admin Panel${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Click the Shield Icon 🛡️ (left sidebar)"
echo "2. Select 'Moderator Panel'"
echo "3. Click 'Verifications' tab at the top"
echo ""

echo -e "${BLUE}Step 6: Start Reviewing Photos${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Click a photo in the left panel"
echo "2. Click 'Run AI Analysis'"
echo "3. Review the quality score and recommendations"
echo "4. Click 'Approve' or 'Reject'"
echo ""

echo -e "${YELLOW}📚 Documentation Files${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${GREEN}→${NC} ADMIN_PHOTO_VERIFICATION_QUICK_START.md"
echo "  Quick reference with visual layouts"
echo ""
echo -e "${GREEN}→${NC} ADMIN_PHOTO_VERIFICATION_GUIDE.md"
echo "  Complete setup and usage documentation"
echo ""
echo -e "${GREEN}→${NC} PHOTO_VERIFICATION_ADMIN_FEATURES.md"
echo "  Feature overview and technical details"
echo ""
echo -e "${GREEN}→${NC} ADMIN_DEPLOYMENT_CHECKLIST.md"
echo "  Pre-launch verification checklist"
echo ""

echo -e "${YELLOW}🎯 Key Features${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✓ Real-time statistics dashboard"
echo "✓ AI-powered photo analysis"
echo "✓ Face detection and quality scoring"
echo "✓ One-click approve/reject workflow"
echo "✓ Admin notes and rejection reasons"
echo "✓ Auto-refresh capability"
echo "✓ Beautiful, intuitive UI"
echo ""

echo -e "${YELLOW}🔧 Admin Account Options${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Option 1: Create Test Moderator (Fastest)"
echo "  cd backend && node create-test-moderator.js"
echo ""
echo "Option 2: Promote Existing User"
echo "  cd backend && node setup-admin.js your.email@example.com ADMIN"
echo ""
echo "Option 3: Direct Database"
echo "  mongosh"
echo "  use spark-dating"
echo "  db.users.updateOne({email:\"email@example.com\"},{\\$set:{role:\"ADMIN\"}})"
echo ""

echo -e "${YELLOW}🚨 Troubleshooting${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Problem: Verifications tab not showing"
echo "→ Verify user role is ADMIN or MODERATOR"
echo "→ Log out and back in"
echo ""
echo "Problem: AI Analysis errors"
echo "→ Check Cloudinary API key in .env"
echo "→ Restart backend server"
echo ""
echo "Problem: Photos won't load"
echo "→ Verify backend running: curl http://localhost:5000/api/health"
echo "→ Check browser console (F12) for errors"
echo ""

echo -e "${YELLOW}📊 Admin Dashboard Breakdown${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Header: Title, refresh button, auto-refresh toggle"
echo "Stats:  Pending | Approved | Rejected | Average Time"
echo "Left:   Photo gallery with quality scores"
echo "Right:  Large preview, AI analysis, decision buttons"
echo ""

echo -e "${GREEN}╔════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  ✨ Setup Complete! You're ready to start reviewing photos.   ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo "Next step: Run the commands from 'Step 1' above!"
echo ""
